# Generated by Django 5.2.7 on 2026-03-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
